### ISSUE TITLE
Create a logo for django girls spb

### ISSUE THREAD

**Issue by bruno-gelb** [DjangoGirlsSPb/logo#1]

**Comment by bruno-gelb** [comment]
@lig @asta-ko any thoughts on designer and/or design?

**Comment by lig** [comment]
I suggest to just stick with the official one for the first time
https://github.com/DjangoGirls/resources/tree/master/Design/Logo

**Comment by bruno-gelb** [comment]
@lig we already has one, it's just not in the repo yet.
